import './globals.css'

import type { Metadata } from 'next'
import { Itim } from 'next/font/google'

const itim = Itim({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => (
  <html lang="en">
    <body className={itim.className}>{children}</body>
  </html>
)

export default RootLayout
