import './globals.css'
import type { Metadata } from 'next'
import { Epilogue } from 'next/font/google'

const font = Epilogue({ subsets: ['latin'], weight: ['500', '700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => (
  <html lang="en">
    <body className={font.className}>{children}</body>
  </html>
)

export default RootLayout
